# Generated by Django 4.1.3 on 2023-04-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('rid', models.CharField(max_length=20)),
                ('espid', models.TextField(max_length=20)),
                ('acesp', models.BooleanField(default=False)),
                ('panelid', models.TextField(max_length=20)),
                ('name', models.TextField(max_length=20)),
                ('value', models.BooleanField(default=False)),
                ('lock', models.BooleanField(default=False)),
                ('ping', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='acdatalogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espid', models.CharField(max_length=20)),
                ('no', models.IntegerField()),
                ('accur', models.FloatField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='datalogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=20)),
                ('ac1cur', models.FloatField()),
                ('ac2cur', models.FloatField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='roomdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=20)),
                ('espid', models.TextField(max_length=20)),
                ('panelid', models.TextField(max_length=20)),
                ('ac1name', models.TextField(max_length=20)),
                ('ac2name', models.TextField(max_length=20)),
                ('ac1', models.BooleanField(default=False)),
                ('acesp', models.BooleanField(default=False)),
                ('ac1lock', models.BooleanField(default=False)),
                ('ac2', models.BooleanField(default=False)),
                ('ac2lock', models.BooleanField(default=False)),
                ('ping', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
