# Generated by Django 4.1.3 on 2023-05-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_registeruserdata_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeruserdata',
            old_name='insitute',
            new_name='institute',
        ),
    ]
